export const MOCK_TRIP = {
  id: 'trip-mock-001',
  userId: 'user-mock-001',
  originCity: 'Hyderabad',
  originCountry: 'India',
  originLat: 17.385,
  originLng: 78.4867,
  destinationCity: 'Dallas',
  destinationCountry: 'US',
  destinationLat: 32.7767,
  destinationLng: -96.797,
  startDate: '2026-03-12',
  endDate: '2026-03-19',
  numDays: 7,
  pace: 'relaxed',
  budgetVibe: '$$$',
  accommodationType: 'hotel',
  preferences: ['food', 'history', 'sightseeing', 'parks'],
  instructions: 'honeymoon trip, vegetarian options preferred',
  numTravelers: 2,
  passportCountry: 'India',
  currency: 'USD',
  status: 'planning', // 'planning' | 'saved'
  shareCode: null,
  createdAt: '2026-03-01T10:00:00Z',

  // ========== PLACES ==========
  places: [
    // RESTAURANTS
    {
      id: 'place-r1',
      googlePlaceId: 'ChIJ_r1',
      name: "Terry Black's BBQ",
      category: 'restaurant',
      lat: 32.7473,
      lng: -96.8268,
      rating: 4.7,
      priceLevel: 2,
      address: '3025 Main St, Dallas, TX 75226',
      photoUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400',
      googleMapsUrl: 'https://maps.google.com/?cid=12345',
      description: 'Legendary pit-smoked BBQ with housemade sides in a rustic setting.',
      famousFor: 'Brisket & beef ribs',
      cuisineType: 'BBQ',
      visitDuration: 60,
      affiliateUrl: 'https://booking.com',
      isInItinerary: true,
      isCustom: false,
      dayNumber: 1,
      timeSlot: '12:30',
    },
    {
      id: 'place-r2',
      googlePlaceId: 'ChIJ_r2',
      name: "Kalachandji's",
      category: 'restaurant',
      lat: 32.7836,
      lng: -96.7647,
      rating: 4.5,
      priceLevel: 1,
      address: '5430 Gurley Ave, Dallas, TX 75223',
      photoUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400',
      googleMapsUrl: 'https://maps.google.com/?cid=12346',
      description: 'All-you-can-eat vegetarian buffet in a serene temple setting.',
      famousFor: 'Vegetarian Indian buffet',
      cuisineType: 'Vegetarian',
      visitDuration: 75,
      affiliateUrl: null,
      isInItinerary: true,
      isCustom: false,
      dayNumber: 2,
      timeSlot: '12:00',
    },
    {
      id: 'place-r3',
      googlePlaceId: 'ChIJ_r3',
      name: 'Uchi Dallas',
      category: 'restaurant',
      lat: 32.8005,
      lng: -96.8012,
      rating: 4.8,
      priceLevel: 3,
      address: '2817 Maple Ave, Dallas, TX 75201',
      photoUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400',
      googleMapsUrl: 'https://maps.google.com/?cid=12347',
      description: 'Award-winning Japanese restaurant with inventive sushi and hot dishes.',
      famousFor: 'Wagyu sashimi & sake pairings',
      cuisineType: 'Japanese',
      visitDuration: 90,
      affiliateUrl: null,
      isInItinerary: true,
      isCustom: false,
      dayNumber: 3,
      timeSlot: '19:00',
    },
    {
      id: 'place-r4',
      googlePlaceId: 'ChIJ_r4',
      name: "Pepe's & Mito's",
      category: 'restaurant',
      lat: 32.748,
      lng: -96.8472,
      rating: 4.6,
      priceLevel: 1,
      address: '2911 Elm St, Dallas, TX 75226',
      photoUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400',
      googleMapsUrl: 'https://maps.google.com/?cid=12348',
      description: 'Authentic Tex-Mex with generous portions and killer margaritas.',
      famousFor: 'Breakfast tacos & enchiladas',
      cuisineType: 'Tex-Mex',
      visitDuration: 60,
      affiliateUrl: null,
      isInItinerary: false,
      isCustom: false,
      dayNumber: null,
      timeSlot: null,
    },
    {
      id: 'place-r5',
      googlePlaceId: 'ChIJ_r5',
      name: 'Cosmic Café',
      category: 'restaurant',
      lat: 32.8072,
      lng: -96.8105,
      rating: 4.4,
      priceLevel: 1,
      address: '2912 Oak Lawn Ave, Dallas, TX 75219',
      photoUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=400',
      googleMapsUrl: 'https://maps.google.com/?cid=12349',
      description: 'Bohemian vegetarian café with Indian-inspired dishes and a patio.',
      famousFor: 'Enchiladas & chai',
      cuisineType: 'Vegetarian',
      visitDuration: 60,
      affiliateUrl: null,
      isInItinerary: true,
      isCustom: false,
      dayNumber: 4,
      timeSlot: '12:30',
    },

    // HOTELS
    {
      id: 'place-h1',
      googlePlaceId: 'ChIJ_h1',
      name: 'The Adolphus Hotel',
      category: 'hotel',
      lat: 32.781,
      lng: -96.7984,
      rating: 4.6,
      priceLevel: 3,
      address: '1321 Commerce St, Dallas, TX 75202',
      photoUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400',
      googleMapsUrl: 'https://maps.google.com/?cid=22345',
      description: 'Historic luxury hotel in downtown Dallas with rooftop pool.',
      famousFor: 'Rooftop pool & 1912 architecture',
      pricePerNight: 289,
      amenities: ['Pool', 'Spa', 'Restaurant', 'Gym', 'Concierge'],
      affiliateUrl: 'https://booking.com/hotel/adolphus',
      affiliatePartner: 'Booking.com',
      isInItinerary: true,
      isCustom: false,
    },
    {
      id: 'place-h2',
      googlePlaceId: 'ChIJ_h2',
      name: 'Hotel Lumen',
      category: 'hotel',
      lat: 32.8396,
      lng: -96.7735,
      rating: 4.3,
      priceLevel: 2,
      address: '6101 Hillcrest Ave, Dallas, TX 75205',
      photoUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=400',
      googleMapsUrl: 'https://maps.google.com/?cid=22346',
      description: 'Boutique hotel near SMU with modern rooms and a lively bar.',
      famousFor: 'Rooftop bar & walkable location',
      pricePerNight: 189,
      amenities: ['Bar', 'Pool', 'Gym', 'Free WiFi'],
      affiliateUrl: 'https://booking.com/hotel/lumen',
      affiliatePartner: 'Booking.com',
      isInItinerary: false,
      isCustom: false,
    },

    // ATTRACTIONS
    {
      id: 'place-a1',
      googlePlaceId: 'ChIJ_a1',
      name: 'Dallas Arboretum',
      category: 'attraction',
      lat: 32.823,
      lng: -96.7165,
      rating: 4.8,
      priceLevel: 2,
      address: '8525 Garland Rd, Dallas, TX 75218',
      photoUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=400',
      googleMapsUrl: 'https://maps.google.com/?cid=32345',
      description: 'Botanical gardens on the shore of White Rock Lake.',
      famousFor: 'Seasonal flower displays & lake views',
      visitDuration: 120,
      ticketPrice: 20,
      affiliateUrl: 'https://getyourguide.com/dallas-arboretum',
      affiliatePartner: 'GetYourGuide',
      isInItinerary: true,
      isCustom: false,
      dayNumber: 2,
      timeSlot: '10:00',
    },
    {
      id: 'place-a2',
      googlePlaceId: 'ChIJ_a2',
      name: 'Sixth Floor Museum',
      category: 'attraction',
      lat: 32.7802,
      lng: -96.8085,
      rating: 4.7,
      priceLevel: 2,
      address: '411 Elm St, Dallas, TX 75202',
      photoUrl: 'https://images.unsplash.com/photo-1569982175971-d92b01cf8694?w=400',
      googleMapsUrl: 'https://maps.google.com/?cid=32346',
      description: 'JFK assassination museum in Dealey Plaza.',
      famousFor: 'JFK history & Dealey Plaza views',
      visitDuration: 90,
      ticketPrice: 24,
      affiliateUrl: 'https://getyourguide.com/sixth-floor',
      affiliatePartner: 'GetYourGuide',
      isInItinerary: true,
      isCustom: false,
      dayNumber: 1,
      timeSlot: '14:00',
    },
    {
      id: 'place-a3',
      googlePlaceId: 'ChIJ_a3',
      name: 'Perot Museum',
      category: 'attraction',
      lat: 32.7869,
      lng: -96.8066,
      rating: 4.7,
      priceLevel: 2,
      address: '2201 N Field St, Dallas, TX 75201',
      photoUrl: 'https://images.unsplash.com/photo-1574958269340-fa927503f3dd?w=400',
      googleMapsUrl: 'https://maps.google.com/?cid=32347',
      description: 'World-class science and nature museum designed by Thom Mayne.',
      famousFor: 'Interactive exhibits & architecture',
      visitDuration: 120,
      ticketPrice: 22,
      affiliateUrl: 'https://getyourguide.com/perot-museum',
      affiliatePartner: 'GetYourGuide',
      isInItinerary: true,
      isCustom: false,
      dayNumber: 3,
      timeSlot: '10:00',
    },
    {
      id: 'place-a4',
      googlePlaceId: 'ChIJ_a4',
      name: 'Deep Ellum',
      category: 'attraction',
      lat: 32.7842,
      lng: -96.7823,
      rating: 4.5,
      priceLevel: 0,
      address: 'Deep Ellum, Dallas, TX',
      photoUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400',
      googleMapsUrl: 'https://maps.google.com/?cid=32348',
      description: 'Vibrant arts district with murals, live music venues, and street food.',
      famousFor: 'Street murals & live music',
      visitDuration: 180,
      ticketPrice: 0,
      affiliateUrl: null,
      isInItinerary: true,
      isCustom: false,
      dayNumber: 4,
      timeSlot: '16:00',
    },
    {
      id: 'place-a5',
      googlePlaceId: 'ChIJ_a5',
      name: 'Reunion Tower',
      category: 'attraction',
      lat: 32.7755,
      lng: -96.8088,
      rating: 4.4,
      priceLevel: 2,
      address: '300 Reunion Blvd E, Dallas, TX 75207',
      photoUrl: 'https://images.unsplash.com/photo-1477346611705-65d1883cee1e?w=400',
      googleMapsUrl: 'https://maps.google.com/?cid=32349',
      description: 'Iconic observation tower with 360° views of the Dallas skyline.',
      famousFor: 'Sunset views & GeO-Deck',
      visitDuration: 60,
      ticketPrice: 25,
      affiliateUrl: null,
      isInItinerary: false,
      isCustom: false,
      dayNumber: null,
      timeSlot: null,
    },
  ],

  // ========== ITINERARY (day-by-day) ==========
  itinerary: [
    {
      dayNumber: 1,
      title: 'Arrival & Downtown Discovery',
      activities: [
        { time: '10:30', type: 'flight', title: 'Arrive at DFW International', detail: 'Flight AA294 · Terminal D', placeId: null },
        { time: '12:00', type: 'hotel', title: 'Check in at The Adolphus', detail: 'Early check-in confirmed', placeId: 'place-h1' },
        { time: '12:30', type: 'food', title: "Lunch at Terry Black's BBQ", detail: 'Famous brisket & ribs — try the beef rib!', placeId: 'place-r1' },
        { time: '14:00', type: 'attraction', title: 'Sixth Floor Museum at Dealey Plaza', detail: 'JFK assassination history. Book tickets in advance.', placeId: 'place-a2' },
        { time: '17:00', type: 'free', title: 'Walk around Dealey Plaza & Downtown', detail: 'Photo ops at the grassy knoll and old courthouse.', placeId: null },
        { time: '19:30', type: 'food', title: 'Dinner — explore nearby', detail: 'Walk the Arts District for dinner options.', placeId: null },
      ],
    },
    {
      dayNumber: 2,
      title: 'Nature & Gardens',
      activities: [
        { time: '09:00', type: 'food', title: 'Breakfast at hotel', detail: 'The Adolphus has excellent breakfast.', placeId: 'place-h1' },
        { time: '10:00', type: 'attraction', title: 'Dallas Arboretum & Botanical Garden', detail: '66 acres of gardens on White Rock Lake. Bring sunscreen!', placeId: 'place-a1' },
        { time: '12:00', type: 'food', title: "Lunch at Kalachandji's", detail: 'Vegetarian buffet in a Hare Krishna temple — unique experience.', placeId: 'place-r2' },
        { time: '14:00', type: 'free', title: 'White Rock Lake Trail', detail: 'Rent bikes or walk the 9-mile loop. Beautiful afternoon activity.', placeId: null },
        { time: '17:00', type: 'free', title: 'Rest & freshen up', detail: 'Back to hotel for pool time.', placeId: 'place-h1' },
        { time: '19:00', type: 'food', title: "Dinner — chef's choice", detail: 'Explore Bishop Arts District restaurants.', placeId: null },
      ],
    },
    {
      dayNumber: 3,
      title: 'Science, Art & Fine Dining',
      activities: [
        { time: '10:00', type: 'attraction', title: 'Perot Museum of Nature and Science', detail: 'Interactive exhibits for all ages. Allow 2-3 hours.', placeId: 'place-a3' },
        { time: '12:30', type: 'food', title: 'Lunch in Victory Park', detail: 'Casual lunch near the museum.', placeId: null },
        { time: '14:00', type: 'attraction', title: 'Dallas Museum of Art', detail: 'Free general admission! World-class collection.', placeId: null },
        { time: '16:00', type: 'free', title: 'Klyde Warren Park', detail: 'Urban park with food trucks and events.', placeId: null },
        { time: '19:00', type: 'food', title: 'Dinner at Uchi Dallas', detail: 'Upscale Japanese — make a reservation. Try the wagyu sashimi.', placeId: 'place-r3' },
      ],
    },
    {
      dayNumber: 4,
      title: 'Arts District & Deep Ellum',
      activities: [
        { time: '09:30', type: 'free', title: 'Morning walk — Katy Trail', detail: '3.5-mile urban trail, great for a morning jog or walk.', placeId: null },
        { time: '12:30', type: 'food', title: 'Lunch at Cosmic Café', detail: 'Bohemian vegetarian café — try the enchiladas.', placeId: 'place-r5' },
        { time: '14:00', type: 'free', title: 'Bishop Arts District', detail: 'Browse boutiques, galleries, and street art.', placeId: null },
        { time: '16:00', type: 'attraction', title: 'Deep Ellum Walking Tour', detail: 'Street murals, live music, craft cocktails.', placeId: 'place-a4' },
        { time: '19:00', type: 'food', title: 'Dinner in Deep Ellum', detail: 'Tons of options — ask the concierge for recs.', placeId: null },
      ],
    },
  ],

  // ========== FLIGHTS ==========
  flights: [
    {
      id: 'flight-1',
      airline: 'American Airlines',
      flightNumber: 'AA 302',
      origin: 'HYD',
      destination: 'DFW',
      departureTime: '2026-03-12T02:30:00',
      arrivalTime: '2026-03-12T10:30:00',
      duration: '18h 0m',
      stops: 1,
      stopCity: 'Doha (DOH)',
      layoverDuration: '2h 30m',
      price: 847,
      currency: 'USD',
      cabinClass: 'Economy',
      baggageIncluded: '1 checked bag',
      bookingUrl: 'https://skyscanner.com/transport/flights/hyd/dfw',
    },
    {
      id: 'flight-2',
      airline: 'Emirates',
      flightNumber: 'EK 526 / EK 221',
      origin: 'HYD',
      destination: 'DFW',
      departureTime: '2026-03-12T04:15:00',
      arrivalTime: '2026-03-12T14:45:00',
      duration: '20h 30m',
      stops: 1,
      stopCity: 'Dubai (DXB)',
      layoverDuration: '3h 15m',
      price: 923,
      currency: 'USD',
      cabinClass: 'Economy',
      baggageIncluded: '2 checked bags',
      bookingUrl: 'https://skyscanner.com/transport/flights/hyd/dfw',
    },
    {
      id: 'flight-3',
      airline: 'Qatar Airways',
      flightNumber: 'QR 501 / QR 729',
      origin: 'HYD',
      destination: 'DFW',
      departureTime: '2026-03-12T03:00:00',
      arrivalTime: '2026-03-12T13:15:00',
      duration: '20h 15m',
      stops: 1,
      stopCity: 'Doha (DOH)',
      layoverDuration: '4h 0m',
      price: 891,
      currency: 'USD',
      cabinClass: 'Economy',
      baggageIncluded: '2 checked bags',
      bookingUrl: 'https://skyscanner.com/transport/flights/hyd/dfw',
    },
  ],

  // ========== COST ESTIMATE ==========
  costEstimate: {
    accommodation: { total: 2023, perNight: 289, nights: 7, label: '7 nights at The Adolphus' },
    food: { total: 560, perDay: 80, label: '$80/day for 2 people' },
    activities: { total: 380, items: ['Arboretum $40', 'Sixth Floor $48', 'Perot Museum $44', 'Deep Ellum free', 'Other $248'] },
    flights: { total: 1694, label: '2x Economy AA 302' },
    localTransport: { total: 200, label: 'Uber/Lyft ~$28/day' },
    total: 4857,
    perPerson: 2429,
    currency: 'USD',
    dailyAvg: 694,
    label: 'estimated',
  },

  // ========== VISA INFO ==========
  visaInfo: {
    visaRequired: true,
    type: 'B1/B2 Tourist Visa',
    validity: '10 years (multiple entry)',
    processing: '3-5 weeks (book DS-160 interview at US Consulate Hyderabad)',
    warnings: ['Apply at least 6 weeks before travel', 'Passport must be valid 6+ months beyond travel dates'],
    checklist: [
      { id: 'ck1', text: 'Valid passport (6+ months)', checked: false },
      { id: 'ck2', text: 'DS-160 form submitted', checked: false },
      { id: 'ck3', text: 'Interview scheduled at US Consulate', checked: false },
      { id: 'ck4', text: 'Bank statements (last 6 months)', checked: false },
      { id: 'ck5', text: 'Hotel booking confirmation', checked: false },
      { id: 'ck6', text: 'Return flight booking', checked: false },
      { id: 'ck7', text: 'Travel insurance', checked: false },
    ],
  },

  // ========== TRAVEL ESSENTIALS ==========
  travelEssentials: {
    language: 'English',
    emergencyNumbers: { police: '911', ambulance: '911', fire: '911' },
    tipping: '15-20% at restaurants, $1-2 for Uber/valet',
    powerPlug: 'Type A/B (120V, 60Hz) — you need a US adapter from India',
    simAdvice: 'Buy a prepaid T-Mobile or Mint Mobile SIM at DFW airport. ~$30 for 10GB.',
    waterSafety: 'Tap water is safe to drink in Dallas.',
    timezone: 'CDT (UTC-5) — 10.5 hours behind India (IST)',
    currencyInfo: 'US Dollar (USD). Cards accepted everywhere. Carry $50 cash for tips.',
    weatherNote: 'March in Dallas: 15-24°C (59-75°F). Light jacket for evenings.',
    dressCode: 'Casual. Comfortable walking shoes essential.',
  },

  // ========== CHAT MESSAGES ==========
  chatMessages: [
    { id: 'msg-1', role: 'assistant', content: "I've planned your 7-day honeymoon trip to Dallas! Check out the tabs for restaurants, hotels, attractions, and your day-by-day itinerary. Want me to adjust anything?", createdAt: '2026-03-01T10:05:00Z' },
  ],
};

// ========== MARKER COLORS ==========
export const MARKER_COLORS = {
  restaurant: '#EF4444',  // red
  hotel: '#3B82F6',       // blue
  attraction: '#10B981',  // green
  cafe: '#F59E0B',        // amber
  outdoor: '#14B8A6',     // teal
};

// ========== TAB CONFIG ==========
export const PLAN_TABS = [
  { id: 'eat', label: 'Where to Eat', icon: '🍽', shortLabel: 'Eat' },
  { id: 'stay', label: 'Where to Stay', icon: '🏠', shortLabel: 'Stay' },
  { id: 'go', label: 'Places to Go', icon: '📍', shortLabel: 'Go' },
  { id: 'flight', label: 'Flight Details', icon: '✈️', shortLabel: 'Flight' },
  { id: 'costs', label: 'Costs & Spending', icon: '💰', shortLabel: 'Costs' },
  { id: 'trip', label: 'About Your Trip', icon: '📋', shortLabel: 'Trip' },
  { id: 'next', label: "What's Next", icon: '➡️', shortLabel: 'Next' },
];

export const PLAN_SECTIONS = [
  { id: 'eat', label: 'Where to Eat', icon: '🍽', shortLabel: 'Eat' },
  { id: 'stay', label: 'Where to Stay', icon: '🏠', shortLabel: 'Stay' },
  { id: 'go', label: 'Places to Go', icon: '📍', shortLabel: 'Go' },
  { id: 'trip', label: 'Your Itinerary', icon: '📋', shortLabel: 'Trip' },
  { id: 'flight', label: 'Flights', icon: '✈️', shortLabel: 'Flight' },
  { id: 'costs', label: 'Costs', icon: '💰', shortLabel: 'Costs' },
  { id: 'next', label: "What's Next", icon: '➡️', shortLabel: 'Next' },
];

// ================================
// Onboarding Demo Trip (Plan Tour)
// ================================
export const ONBOARDING_DEMO_TRIP = {
  id: 'demo',
  origin_city: 'Dallas',
  origin_country: 'US',
  origin_lat: 32.7767,
  origin_lng: -96.797,
  destination_city: 'Seattle',
  destination_country: 'US',
  destination_lat: 47.6062,
  destination_lng: -122.3321,
  start_date: '2026-04-15',
  end_date: '2026-04-20',
  num_days: 5,
  num_travelers: 2,
  pace: 'moderate',
  budget_vibe: '$$$',
  status: 'planning',
  currency: 'USD',
  narrative:
    "A 5-day Pacific Northwest adventure exploring Seattle's iconic landmarks, fresh seafood scene, and stunning natural beauty.",
  itinerary: {
    itinerary: [
      {
        day_number: 1,
        title: 'Arrival & Downtown',
        activities: [
          {
            time: '10:00 AM',
            title: 'Pike Place Market',
            type: 'attraction',
            detail:
              'Explore the iconic market, watch fish throwing, and grab coffee nearby.',
            place_id: 'demo_pike',
          },
          {
            time: '12:30 PM',
            title: 'Piroshky Piroshky',
            type: 'food',
            detail: 'Famous Russian bakery right in Pike Place.',
            place_id: 'demo_piroshky',
          },
          {
            time: '2:00 PM',
            title: 'Check in at Hotel',
            type: 'hotel',
            detail: 'Settle in and freshen up.',
            place_id: 'demo_hotel',
          },
          {
            time: '7:00 PM',
            title: 'The Walrus and the Carpenter',
            type: 'food',
            detail: 'Oysters and craft cocktails in Ballard.',
            place_id: 'demo_walrus',
          },
        ],
      },
      {
        day_number: 2,
        title: 'Space Needle & Beyond',
        activities: [
          {
            time: '9:00 AM',
            title: 'Space Needle',
            type: 'attraction',
            detail: 'Panoramic views of the city and Puget Sound.',
            place_id: 'demo_needle',
          },
          {
            time: '11:30 AM',
            title: 'Chihuly Garden and Glass',
            type: 'attraction',
            detail: 'Stunning glass art installations.',
            place_id: 'demo_chihuly',
          },
          {
            time: '1:00 PM',
            title: 'Din Tai Fung',
            type: 'food',
            detail: 'Soup dumplings and noodles.',
            place_id: 'demo_dintaifung',
          },
        ],
      },
    ],
  },
  cost_estimate: {
    accommodation: { total: 1200, per_night: 240 },
    food: { total: 500, per_day: 100 },
    activities: { total: 300, per_day: 60 },
    local_transport: { total: 150, per_day: 30 },
    flights: { total: 400, per_person: 200 },
    total: 2550,
    per_person: 1275,
  },
  transport_mode: 'flight',
};

export const ONBOARDING_DEMO_PLACES = [
  {
    id: 'demo_pike',
    google_place_id: 'demo_pike',
    googlePlaceId: 'demo_pike',
    name: 'Pike Place Market',
    category: 'attraction',
    rating: 4.6,
    address: '85 Pike St, Seattle, WA',
    lat: 47.6097,
    lng: -122.3425,
    is_in_itinerary: true,
    photo_url: null,
  },
  {
    id: 'demo_piroshky',
    google_place_id: 'demo_piroshky',
    googlePlaceId: 'demo_piroshky',
    name: 'Piroshky Piroshky',
    category: 'restaurant',
    rating: 4.5,
    address: '1908 Pike Pl, Seattle, WA',
    lat: 47.6101,
    lng: -122.3426,
    is_in_itinerary: true,
    photo_url: null,
  },
  {
    id: 'demo_needle',
    google_place_id: 'demo_needle',
    googlePlaceId: 'demo_needle',
    name: 'Space Needle',
    category: 'attraction',
    rating: 4.5,
    address: '400 Broad St, Seattle, WA',
    lat: 47.6205,
    lng: -122.3493,
    is_in_itinerary: true,
    photo_url: null,
  },
  {
    id: 'demo_walrus',
    google_place_id: 'demo_walrus',
    googlePlaceId: 'demo_walrus',
    name: 'The Walrus and the Carpenter',
    category: 'restaurant',
    rating: 4.4,
    address: '4743 Ballard Ave NW, Seattle, WA',
    lat: 47.666,
    lng: -122.3842,
    is_in_itinerary: true,
    photo_url: null,
  },
  {
    id: 'demo_chihuly',
    google_place_id: 'demo_chihuly',
    googlePlaceId: 'demo_chihuly',
    name: 'Chihuly Garden and Glass',
    category: 'attraction',
    rating: 4.7,
    address: '305 Harrison St, Seattle, WA',
    lat: 47.6206,
    lng: -122.3509,
    is_in_itinerary: true,
    photo_url: null,
  },
  {
    id: 'demo_hotel',
    google_place_id: 'demo_hotel',
    googlePlaceId: 'demo_hotel',
    name: 'The Edgewater Hotel',
    category: 'hotel',
    rating: 4.3,
    address: '2411 Alaskan Way, Seattle, WA',
    lat: 47.6127,
    lng: -122.3565,
    is_in_itinerary: true,
    photo_url: null,
  },
  {
    id: 'demo_dintaifung',
    google_place_id: 'demo_dintaifung',
    googlePlaceId: 'demo_dintaifung',
    name: 'Din Tai Fung',
    category: 'restaurant',
    rating: 4.6,
    address: 'Downtown Seattle, WA',
    lat: 47.6076,
    lng: -122.3375,
    is_in_itinerary: true,
    photo_url: null,
  },
];


